[package]
name = "extracing-example"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrometracer = { path = "../chrometracer" }
